#!/bin/bash

# Publish badge JSON files to GitHub Pages
# Usage: ./scripts/publish-badges-to-github-pages.sh

set -e

BADGES_DIR="badges-json"
RESULTS_DIR="test-results"
GH_PAGES_DIR="gh-pages"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "📤 Publishing badges to GitHub Pages..."
echo ""

# Check if badges directory exists
if [ ! -d "$BADGES_DIR" ]; then
    echo "❌ Error: $BADGES_DIR directory not found"
    echo "Run ./scripts/run-integration-tests.sh first"
    exit 1
fi

# Get GitHub repo info from git remote
REPO_URL=$(git config --get remote.origin.url)
if [ -z "$REPO_URL" ]; then
    echo "❌ Error: Could not determine GitHub repository"
    echo "Make sure you're in a git repository with a remote named 'origin'"
    exit 1
fi

# Extract username and repo name
if [[ $REPO_URL =~ github\.com[:/]([^/]+)/([^/.]+) ]]; then
    USERNAME="${BASH_REMATCH[1]}"
    REPO="${BASH_REMATCH[2]}"
else
    echo "❌ Error: Could not parse GitHub repository URL"
    exit 1
fi

echo "Repository: $USERNAME/$REPO"
echo ""

# Clone or update gh-pages branch
if [ -d "$GH_PAGES_DIR" ]; then
    echo "Updating existing gh-pages directory..."
    cd "$GH_PAGES_DIR"
    git fetch origin gh-pages
    git reset --hard origin/gh-pages
    cd ..
else
    echo "Cloning gh-pages branch..."
    git clone -b gh-pages "$REPO_URL" "$GH_PAGES_DIR" 2>/dev/null || {
        echo "gh-pages branch doesn't exist. Creating it..."
        mkdir -p "$GH_PAGES_DIR"
        cd "$GH_PAGES_DIR"
        git init
        git checkout -b gh-pages
        git remote add origin "$REPO_URL"
        cd ..
    }
fi

# Copy badge files
echo "Copying badge files..."
mkdir -p "$GH_PAGES_DIR/badges"
cp -r "$BADGES_DIR"/* "$GH_PAGES_DIR/badges/"

# Create index page for badges
cat > "$GH_PAGES_DIR/badges/index.html" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ML Container Creator - Test Status</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }
        h1 { color: #333; }
        .timestamp { color: #666; font-size: 0.9em; }
        .badges { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 20px; margin-top: 30px; }
        .badge-card {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .badge-card h3 { margin-top: 0; color: #333; }
        .badge-card img { margin: 10px 0; }
        .badge-card code {
            display: block;
            background: #f5f5f5;
            padding: 10px;
            border-radius: 4px;
            font-size: 0.85em;
            overflow-x: auto;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <h1>🧪 ML Container Creator - Integration Test Status</h1>
    <p class="timestamp">Last updated: $TIMESTAMP</p>
    
    <div class="badges">
EOF

# Add badge cards for each configuration
for badge_file in "$BADGES_DIR"/*.json; do
    if [ -f "$badge_file" ]; then
        filename=$(basename "$badge_file")
        config_name="${filename%.json}"
        badge_url="https://${USERNAME}.github.io/${REPO}/badges/${filename}"
        
        cat >> "$GH_PAGES_DIR/badges/index.html" <<EOF
        <div class="badge-card">
            <h3>$config_name</h3>
            <img src="https://img.shields.io/endpoint?url=${badge_url}" alt="$config_name">
            <code>![${config_name}](https://img.shields.io/endpoint?url=${badge_url})</code>
        </div>
EOF
    fi
done

cat >> "$GH_PAGES_DIR/badges/index.html" <<EOF
    </div>
    
    <hr style="margin: 40px 0;">
    <p style="color: #666; font-size: 0.9em;">
        Generated by <a href="https://github.com/${USERNAME}/${REPO}">ML Container Creator</a>
    </p>
</body>
</html>
EOF

# Commit and push
cd "$GH_PAGES_DIR"

git add badges/
git config user.name "$(git config user.name || echo 'Integration Tests')"
git config user.email "$(git config user.email || echo 'tests@localhost')"
git commit -m "Update integration test badges - $TIMESTAMP" || {
    echo "⚠️  No changes to commit"
    cd ..
    exit 0
}

echo ""
echo "📤 Pushing to GitHub..."
git push origin gh-pages

cd ..

echo ""
echo "✅ Badges published successfully!"
echo ""
echo "🌐 View badges at:"
echo "   https://${USERNAME}.github.io/${REPO}/badges/"
echo ""
echo "📋 Badge URLs for README:"
for badge_file in "$BADGES_DIR"/*.json; do
    if [ -f "$badge_file" ]; then
        filename=$(basename "$badge_file")
        config_name="${filename%.json}"
        echo "   ![${config_name}](https://img.shields.io/endpoint?url=https://${USERNAME}.github.io/${REPO}/badges/${filename})"
    fi
done
